package communication;

import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import java.util.UUID;

public class Header {
    private static final String VERSION = "5.3";
    private static final String USERNAME = "guest";

    private String session = "";
    private String msgType = "";
    private String version = VERSION;
    private String username = USERNAME;
    private String date = "";
    private String msgId = "";


    /**
     * Nullary constructor for deserialization purposes
     */
    public Header() {

    }

    /**
     * Create header with specific msgType, inheriting properties
     * like session, version and username from the parentHeader.
     * Date and msgId are generated by now() and UUID.
     */
    public Header(String msgType, Header parentHeader) {
		this.session = parentHeader.getSession();
		this.msgType = msgType;
        this.version = parentHeader.getVersion();
        this.username = parentHeader.getUsername();
        
        this.date = ZonedDateTime.now().format(DateTimeFormatter.ISO_INSTANT);
        this.msgId = String.valueOf(UUID.randomUUID());
    }

    public String getSession() {
        return session;
    }

    public String getMsgType() {
        return msgType;
    }

    public String getVersion() {
        return version;
    }

    public String getUsername() {
        return username;
    }

    public String getDate() {
        return date;
    }

    public String getMsgId() {
        return msgId;
    }

    @Override
    public String toString() {
       return "Header[" + "session=" + session + ", type=" + msgType + ", version=" + version + ", username=" + username + ", date=" + date + ", msgId=" + msgId + "]";
    }
}
